apiVersion: v1
kind: ServiceAccount
metadata:
  name: mini-task-controller
  namespace: mini-task-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mini-task-controller
rules:

- apiGroups: ["minitask.myorg.dev"]
  resources: ["taskruns","tasks"]
  verbs: ["get","list","watch","update","patch"]

- apiGroups: ["minitask.myorg.dev"]
  resources: ["taskruns/status"]
  verbs: ["update","patch"]

- apiGroups: ["minitask.myorg.dev"]
  resources: ["taskruns/finalizers"]
  verbs: ["update","patch"]

- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","get","list","watch"]

- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]

- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get","list","create","update","delete","patch","watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mini-task-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mini-task-controller
subjects:
- kind: ServiceAccount
  name: mini-task-controller
  namespace: mini-task-system